// starters/apps/starter-partytown/src/entry.ssr.tsx
import { renderToString, RenderOptions } from '@builder.io/qwik/server';
import { manifest } from '@qwik-client-manifest';
import { Root } from './root';

/**
 * Qwik server-side render function.
 */
export function render(opts: RenderOptions) {
  return renderToString(<Root />, {
    manifest,
    qwikLoader: {
      events: ['click', 'keyup', 'expensiveComputationDone'],
    },
    ...opts,
  });
}

// starters/apps/starter-partytown-test/src/entry.ssr.tsx
import { manifest } from "@qwik-client-manifest";
import { RenderOptions, renderToStream } from "@qwikdev/core/server";
import Root from "./root";

/**
 * Qwik server-side render function.
 */
export default function (opts: RenderOptions) {
  return renderToStream(<Root />, {
    manifest,
    ...opts,
  });
}
