// starters/apps/qwikcity-test.prod/src/entry.ssr.tsx
import {
  renderToStream,
  type RenderToStreamOptions,
} from "@builder.io/qwik/server";
import { manifest } from "@qwik-client-manifest";
import Root from "./root";

export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    base: "/qwikcity-test.prod/build/",
    ...opts,
  });
}

// starters/apps/qwikcity-test/src/entry.ssr.tsx
import { manifest } from "@qwik-client-manifest";
import {
  renderToStream,
  type RenderToStreamOptions,
} from "@qwikdev/core/server";
import Root from "./root";

export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    base: "/qwikcity-test/build/",
    ...opts,
  });
}
