// packages/qwik-preact/src/preact/qwikify.tsx
import {
  component$,
  implicit$FirstArg,
  NoSerialize,
  noSerialize,
  QRL,
  useTask$,
  SkipRender,
  useSignal,
  Slot,
  RenderOnce,
  useStylesScoped$,
} from '@builder.io/qwik';

import { isBrowser, isServer } from '@builder.io/qwik/build';
import type { FunctionComponent } from 'preact';
import * as client from './client';
import { renderFromServer } from './server-render';
import { getHostProps, main, mainExactProps, useWakeupSignal } from './slot';
import type { Internal, QwikifyOptions, QwikifyProps, PreactRoot } from './types';

export function qwikifyQrl<PROPS extends {}>(
  preactCmp$: QRL<FunctionComponent<PROPS & { children?: any }>>,
  opts?: QwikifyOptions
) {
  return component$<QwikifyProps<PROPS>>((props) => {
    const { scopeId } = useStylesScoped$(
      `q-slot{display:none} q-slotc,q-slotc>q-slot{display:contents}`
    );
    const hostRef = useSignal<Element>();
    const slotRef = useSignal<Element>();
    const internalState = useSignal<NoSerialize<Internal<PROPS>>>();
    const [signal, isClientOnly] = useWakeupSignal(props, opts);
    const hydrationKeys = {};
    const TagName = opts?.tagName ?? ('qwik-preact' as any);

    // Watch takes cares of updates and partial hydration
    useTask$(async ({ track }) => {
      const trackedProps = track(() => ({ ...props }));
      track(signal);

      if (!isBrowser) {
        return;
      }

      // Update
      if (internalState.value) {
        if (internalState.value.root) {
          internalState.value.root.render(
            main(slotRef.value, scopeId, internalState.value.cmp, trackedProps)
          );
        }
      } else {
        let root: PreactRoot | undefined = undefined;
        const Cmp = await preactCmp$.resolve();
        const hostElement = hostRef.value;
        if (hostElement) {
          // hydration
          if (isClientOnly) {
            root = client.createRoot(hostElement);
          } else {
            root = client.hydrateRoot(
              hostElement,
              mainExactProps(slotRef.value, scopeId, Cmp, hydrationKeys)
            );
          }
          if (isClientOnly || signal.value === false) {
            root.render(main(slotRef.value, scopeId, Cmp, trackedProps));
          }
        }
        internalState.value = noSerialize({
          cmp: Cmp,
          root,
        });
      }
    });

    if (isServer && !isClientOnly) {
      const jsx = renderFromServer(
        TagName,
        preactCmp$,
        scopeId,
        props,
        hostRef,
        slotRef,
        hydrationKeys
      );
      return <RenderOnce>{jsx}</RenderOnce>;
    }

    return (
      <RenderOnce>
        <TagName
          {...getHostProps(props)}
          ref={(el: Element) => {
            if (isBrowser) {
              queueMicrotask(() => {
                const internalData = internalState.value;
                if (internalData && !internalData.root) {
                  const root = (internalData.root = client.createRoot(el));
                  root.render(main(slotRef.value, scopeId, internalData.cmp, props));
                }
              });
            } else {
              hostRef.value = el;
            }
          }}
        >
          {SkipRender}
        </TagName>
        <q-slot ref={slotRef}>
          <Slot></Slot>
        </q-slot>
      </RenderOnce>
    );
  });
}

export const qwikify$ = /*#__PURE__*/ implicit$FirstArg(qwikifyQrl);

// packages/qwik-angular/src/angular/qwikify.tsx
import {
  component$,
  implicit$FirstArg,
  RenderOnce,
  Slot,
  type NoSerialize,
  type QRL,
  useSignal,
  useTask$,
  noSerialize,
  useVisibleTask$,
  useStylesScoped$,
} from '@builder.io/qwik';
import { isBrowser, isServer } from '@builder.io/qwik/build';
import type { Type } from '@angular/core';
import { ClientRenderer } from './client';
import { getHostProps, useWakeupSignal } from './slot';
import type { Internal, QwikifyOptions, QwikifyProps } from './types';
import { renderFromServer } from './server';

export function qwikifyQrl<PROPS extends {}>(
  angularCmp$: QRL<Type<unknown>>,
  opts?: QwikifyOptions
) {
  // TODO: check if provided angularCmp$ is a standalone angular component
  return component$<QwikifyProps<PROPS>>((props) => {
    useStylesScoped$(`q-slot:not([projected]){display:none}`);
    const hostRef = useSignal<Element>();
    const slotRef = useSignal<Element>();
    const internalState = useSignal<NoSerialize<Internal>>();
    const [signal, isClientOnly] = useWakeupSignal(props, opts);
    const TagName: any = opts?.tagName ?? 'qwik-angular';

    useVisibleTask$(({ cleanup }) => {
      cleanup(() => internalState.value?.renderer.appRef?.destroy());
    });

    // Watch takes care of updates and partial hydration
    useTask$(async ({ track }) => {
      const trackedProps = track(() => ({ ...props }));
      track(signal);
      if (!isBrowser) {
        return;
      }

      // Update
      if (internalState.value) {
        if (internalState.value.renderer) {
          internalState.value.renderer.setInputProps(trackedProps);
        }
      } else {
        const component = await angularCmp$.resolve();
        const hostElement = hostRef.value;
        const renderer = new ClientRenderer(component, trackedProps);
        if (hostElement) {
          await renderer.render(hostElement, slotRef.value);
        }
        internalState.value = noSerialize({
          renderer,
        });
      }
    });

    if (isServer && !isClientOnly) {
      const jsx = renderFromServer(TagName, angularCmp$, hostRef, slotRef, props);
      return <RenderOnce>{jsx}</RenderOnce>;
    }

    return (
      <RenderOnce>
        <TagName
          {...getHostProps(props)}
          ref={(el: Element) => {
            queueMicrotask(async () => {
              // queueMicrotask is needed in order to have "slotRef" defined
              hostRef.value = el;
              if (isBrowser && internalState.value) {
                internalState.value.renderer &&
                  (await internalState.value.renderer.render(el, slotRef.value, props));
              }
            });
          }}
        ></TagName>
        <q-slot ref={slotRef}>
          <Slot></Slot>
        </q-slot>
      </RenderOnce>
    );
  });
}

export const qwikify$ = /*#__PURE__*/ implicit$FirstArg(qwikifyQrl);
