// starters/apps/qwikcity-test/src/routes/(common)/products/404.tsx
import { useLocation, type DocumentHead } from "@qwikdev/city";
import { component$ } from "@qwikdev/core";

export default component$(() => {
  const { params } = useLocation();

  return (
    <div>
      <h1>Product {params.id} not found</h1>
    </div>
  );
});

export const head: DocumentHead = ({ params }) => {
  return {
    title: `Product ${params.id} Not Found`,
  };
};

// starters/apps/qwikcity-test/src/routes/products/404.tsx
import { component$ } from '@builder.io/qwik';
import { useLocation, DocumentHead } from '@builder.io/qwik-city';

export default component$(() => {
  const { params } = useLocation();

  return (
    <div>
      <h1>Product {params.id} not found</h1>
    </div>
  );
});

export const head: DocumentHead = ({ params }) => {
  return {
    title: `Product ${params.id} Not Found`,
  };
};
