// starters/apps/qwikcity-test/src/entry.ssr.tsx
import { manifest } from "@qwik-client-manifest";
import {
  renderToStream,
  type RenderToStreamOptions,
} from "@qwikdev/core/server";
import Root from "./root";

export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    base: "/qwikcity-test/build/",
    ...opts,
  });
}

// starters/features/qwik-react/src/entry.ssr.tsx
import type { RenderToStreamOptions } from '@builder.io/qwik/server';
import { renderToStream } from '@builder.io/qwik-react';
import { manifest } from '@qwik-client-manifest';
import Root from './root';

export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    ...opts,
  });
}
