// packages/devtools/ui/src/entry.ssr.tsx
/**
 * WHAT IS THIS FILE?
 *
 * SSR entry point, in all cases the application is rendered outside the browser, this
 * entry point will be the common one.
 *
 * - Server (express, cloudflare...)
 * - npm run start
 * - npm run preview
 * - npm run build
 *
 */
import { manifest } from '@qwik-client-manifest';
import {
  renderToStream,
  type RenderToStreamOptions,
} from '@qwik.dev/core/server';
import Root from './root';

export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    ...opts,
  });
}

// packages/qwik-labs/src/entry.ssr.tsx
/**
 * WHAT IS THIS FILE?
 *
 * SSR entry point, in all cases the application is rendered outside the browser, this entry point
 * will be the common one.
 *
 * - Server (express, cloudflare...)
 * - `npm run start`
 * - `npm run preview`
 * - `npm run build`
 */
import { manifest } from '@qwik-client-manifest';
import { renderToStream, type RenderToStreamOptions } from '@qwikdev/core/server';
import Root from './root';

export default function (opts: RenderToStreamOptions) {
  return renderToStream(<Root />, {
    manifest,
    ...opts,
  });
}
