// starters/apps/blank/src/entry.ssr.tsx
import { renderToString, RenderOptions } from '@builder.io/qwik/server';
import { manifest } from '@qwik-client-manifest';
import Root from './root';

/**
 * Server-Side Render method to be called by a server.
 */
export function render(opts?: RenderOptions) {
  // Render the Root component to a string
  // Pass in the manifest that was generated from the client build
  return renderToString(<Root />, {
    manifest,
    ...opts,
  });
}

// packages/qwik-react/src/entry.ssr.tsx
import { manifest } from '@qwik-client-manifest';
import { renderToStream, type RenderToStreamOptions } from '@qwikdev/core/server';
import { Root } from './root';

/** Server-Side Render method to be called by a server. */
export default function (opts: RenderToStreamOptions) {
  // Render the Root component to a string
  // Pass in the manifest that was generated from the client build
  return renderToStream(<Root />, {
    manifest,
    ...opts,
  });
}
