// examples/qwik-cache-examples-gallery/src/root.tsx
import { component$ } from '@qwik.dev/core';
import { DocumentHeadTags, RouterOutlet, useQwikRouter } from '@qwik.dev/router';

export default component$(() => {
  useQwikRouter();

  return (
    <>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        <DocumentHeadTags />
      </head>
      <body class="m-0 bg-slate-50 font-sans text-slate-900 antialiased">
        <RouterOutlet />
      </body>
    </>
  );
});

// starters/apps/qwik-city/src/root.tsx
import { App } from './components/app/app';

import './global.css';

export const Root = () => {
  return (
    <html lang="en">
      <head>
        <Head />
      </head>
      <body>
        <App />
      </body>
    </html>
  );
};


const Head = () => (
  <>
    <meta charSet="utf-8" />

    <title>QwikCity Example</title>
    <meta name="viewport" content="width=device-width" />

    <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
    <link rel="icon" href="/favicons/favicon.svg" type="image/svg+xml" />

    <meta property="og:locale" content="en_US" />
  </>
);
