// packages/qwik-city/runtime/src/root.tsx
import cityPlan from '@qwik-city-plan';
import { Content, Html } from '~qwik-city-runtime';
import { Head } from './app/components/head/head';
import './global.css';

export default function Root() {
  return (
    <Html lang="en" cityPlan={cityPlan}>
      <Head />
      <body>
        <Content />
      </body>
    </Html>
  );
}

// starters/apps/qwik-city/src/root.tsx
import { Content, Html } from '@builder.io/qwik-city';
import cityPlan from '@qwik-city-plan';
import { Head } from '~/components/head/head';

import './global.css';

export default () => {
  return (
    <Html lang="en" cityPlan={cityPlan}>
      <Head />
      <body>
        <Content />
      </body>
    </Html>
  );
};
